version: '3.7'
services:
  server:
    tty: true
    build:
      context: ./server
      target: 'development'
    networks:
      - backend
    volumes:
      - ./server/src:/go/src/vault-generator

  client:
    tty: true
    build:
      context: ./client
      target: 'development'
    ports:
      - 3000:3000
    networks:
      - backend
    volumes:
      - ./client:/app

      - node_modules:/app/node_modules

networks:
  backend:

volumes:
  node_modules:
